spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/graduate-work
    password: 1234567890
    username: AccountTest

  liquibase:
    change-log: liquibase/changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate

path:
  image: C:\\avatar